### PR TITLE
Move the worker bits to a framework

### PR DESCRIPTION
**Pull request by jsorge**
I'd like to get at the relevant parts that extract build settings from a command line app, so I extracted them to a framework that is initially used only by the Mac app. But from here we can make Cocoapods or Carthage support happen fairly easily for inclusion in other projects.

I also added the nullability annotation to the framework headers for kicks 😄

### CODE REVIEW

**Comment by jsorge** [comment]
I like the idea of having a CLI app do all the work. It should definitely stay as part of this repo (no reason to break it out in my mind) and others that need to use it can use this repo as a submodule if they want (or just embed the binary directly).

I’m not planning on adding anything to this repo externally. My goal is to have some way to get the path to an Xcode project and have it spit out a `project.yml` file and xcconfigs that can be ingested by [xcodegen](https://github.com/yonaskolb/XcodeGen).

**Comment by dempseyatgithub** [comment]
It sounds like you are looking to build is something that will take an existing Xcode project and convert it into something suitable for use by xcodegen.

So, in essence a tool that would allow you to round-trip between an Xcode project and xcodegen. (The tool goes Xcode project -> xcodegen, xcodegen goes the other way.)  Am I understanding that correctly?

**Comment by jsorge** [comment]
Yep!

**Comment by dempseyatgithub** [comment]
Thanks for saying hi on Micro.blog! I definitely see your point - a tool that would make it easy to get started with xcodegen would be useful.

One side-effect of adding that capability to this project is that, to remain well-behaved and up to date, this project would be committing to track changes and new capabilities of the xcodegen project and the project.yml file format over time. I think that's out of scope for this project.

I think what you describe is a very similar but separate tool, since it will need to track and update for project.yml changes. It also seems that it would make sense for xcodegen to have this capability itself - either as an option of xcodegen or as a companion CLI utility in the xcodegen project.

Maybe the best approach is for you to use Build Setting Extractor code as a starting point and building 'ymlgen' as a completely separate project. I am sorry to be so long-winded about this. Just trying to keep from bringing on unexpected maintenance requirements.

**Comment by jsorge** [comment]
Oh entirely. My hope is to have my xcode project parser generate its own yaml. I was going to use this project solely for extracting the configs from an existing project, then link to those new files in the yaml for xcodegen.

**Comment by jsorge** [comment]
So the next step would be to make the command line target, and call that from the main app. I don’t _think_ that’s a huge bit of work but we shall see 🙂

**Comment by dempseyatgithub** [comment]
Give me a couple of days and I'll see if I have time to do up the command-line tool for BuildSettingExtractor.

My initial draft for the CLI was:

`buildsettingextractor -project /path/to/projectfile -projectname XXX -sharedname XXX -separator X -openWhenFinished -includeInfoComments /path/to/destination/folder
`

The -projectname -sharedname -separator -openWhenFinished and -includeInfoComments are all optional. The defaults would be more appropriate to the command line, not opening the folder in Finder, not including comments for something that will just be ingested into another tool.

The bare bones command would be:

`buildsettingextractor -project /path/to/projectfile /path/to/destination/folder
`
Open to any suggestions.

**Comment by dempseyatgithub** [comment]
@jsorge FYI, I have a CLI working. I will want to clean it up before putting it on master, but I could push a branch if you would use it.

**Comment by dempseyatgithub** [comment]
Thanks @jsorge for the pull request and for giving a lot to think about.

As described above, to keep the project less complex and more compact, the project will just use target inclusion of the core files instead of factoring out into a framework. (At least at this time.)

Closing this PR, but with the intent recorded in Issue #17.

**Pull request closed without merging**
