### PR TITLE
Remove async extraction to avoid exc_bad_access runtime crash.

### PR DESCRIPTION
**Pull request by thomasuster**

### CODE REVIEW

**Comment by dempseyatgithub** [comment]
Are you running this on 10.9 or earlier?

**Comment by thomasuster** [comment]
screen shot 2015-05-11 at 6 25 11 pm

**Comment by dempseyatgithub** [comment]
Thanks for sending the pull request. I ended up being able to fix the issue a different way where I didn’t have to disable background processing.  The details are in Issue #2. So, I’m going to close your pull request, but thanks again for sending it. It definitely motivated me to make this fix sooner rather than later.

**Comment by thomasuster** [comment]
You're welcome

**Pull request closed without merging**
